# Generated by Django 4.1.1 on 2022-09-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refyear', models.IntegerField(blank=True, default=2022, null=True)),
                ('sow_start_date', models.DateField(blank=True, null=True)),
                ('sow_end_date', models.DateField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, default=1, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting.county')),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueChain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValuechainVariety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('release_name', models.CharField(max_length=256)),
                ('valuechain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting.valuechain')),
            ],
        ),
        migrations.CreateModel(
            name='PlantingDatePlanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_maturity_period', models.IntegerField(blank=True, default=90, null=True)),
                ('max_maturity_period', models.IntegerField(blank=True, default=90, null=True)),
                ('first_weeding_after_days', models.IntegerField(blank=True, default=90, null=True)),
                ('second_weeding_after_days', models.IntegerField(blank=True, default=90, null=True)),
                ('ferlizer_application_recommendation', models.TextField(blank=True, null=True)),
                ('min_expected_yield', models.FloatField(blank=True, default=1.9, null=True)),
                ('max_expected_yield', models.FloatField(blank=True, default=1.9, null=True)),
                ('areas_for_optimal_production', models.CharField(blank=True, max_length=256, null=True)),
                ('special_attributes', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.cropcalendar')),
            ],
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='subcounty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.subcounty'),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='valuechain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting.valuechain'),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.ward'),
        ),
    ]
