# Generated by Django 4.1.1 on 2022-09-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingDatePlannerC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refyear', models.IntegerField(blank=True, default=2022, null=True)),
                ('sow_start_date', models.DateField(blank=True, null=True)),
                ('sow_end_date', models.DateField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, default=1, null=True)),
                ('min_maturity_period', models.IntegerField(blank=True, default=90, null=True)),
                ('max_maturity_period', models.IntegerField(blank=True, default=90, null=True)),
                ('first_weeding_after_days', models.IntegerField(blank=True, default=90, null=True)),
                ('second_weeding_after_days', models.IntegerField(blank=True, default=90, null=True)),
                ('ferlizer_application_recommendation', models.TextField(blank=True, null=True)),
                ('min_expected_yield', models.FloatField(blank=True, default=1.9, null=True)),
                ('max_expected_yield', models.FloatField(blank=True, default=1.9, null=True)),
                ('areas_for_optimal_production', models.CharField(blank=True, max_length=256, null=True)),
                ('special_attributes', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting.county')),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.subcounty')),
                ('vc_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting.valuechainvariety')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.ward')),
            ],
        ),
    ]
