# Generated by Django 4.1.1 on 2022-09-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0002_plantingdateplannerc'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingdateplannerc',
            name='valuechain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.valuechain'),
        ),
        migrations.AlterField(
            model_name='plantingdateplannerc',
            name='vc_variety',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
